name: Update from Upstream

on:
  workflow_dispatch:
  cron:
    - '0 0 * * *'

jobs:
  update_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: Fetch Upstream
        run: git fetch upstream
      - name: Merge Upstream
        run: git merge upstream/main
      - name: Push Changes
        run: git push origin main